config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "show", to: "static_pages#show"
    get "help", to: "static_pages#help"
    get "about", to: "static_pages#about"
    get "contact", to: "static_pages#contact"
    get "signup", to: "users#new"
    post "signup", to: "users#create"
    get "login", to: "sessions#new"
    post "login", to: "sessions#create"
    delete "logout", to: "sessions#destroy"
    get "password_resets/new"
    get "password_resets/edit"

    resources :account_activations, only: :edit
    resources :password_resets, only: %i(new create edit update)
    resources :microposts, only: %i(create destroy new)

    resources :users do
      member do
        get :following, :followers
      end
    end
    resources :relationships, only: %i(create destroy)
    resources :comments
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :micropost
  belongs_to :parent, class_name: "Comment", optional: true
  has_many :replies, class_name: "Comment", foreign_key: :parent_id, dependent: :destroy
  validates :content, presence: true

  scope :newest, -> { order created_at: :desc }

  delegate :name, to: :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_micropost, only: %i(create)
  before_action :load_comment, only: %i(edit update destroy)

  def new
    # @micropost = Micropost.find(params[:micropost_id])
    @micropost = Comment.find_by(id: params[:parent_id]).micropost
    @comment = @micropost.comments.new(parent_id: params[:parent_id])
  end

  def create
    @comment = current_user.comments.build comment_params
    @comment.micropost_id = @micropost.id
    if @comment.save
      flash[:success] = "binh luan thanh cong"
      redirect_to show_path(id: @comment.micropost_id)
    else
      flash[:warning] = "binh luan that bai"
      redirect_to static_page_path params[:micropost_id]
    end
  end

  def edit
    @comment = Comment.find_by id: params[:id]
  end

  def update
    if @comment.update comment_params
      flash[:success] = "chinh sua comment thanh cong"
      redirect_to show_path(id: @comment.micropost_id)
    else
      flash.now[:warning] = "chinh sua that bai"
      render :edit
    end
  end

  def destroy
    if @comment&.destroy
      flash[:success] = "Xoa thanh cong"
    else
      flash[:danger] = "xoa that bai"
    end
    redirect_to show_path(id: @comment.micropost_id)
  end

  private

  def comment_params
    params.require(:comment).permit(:content, :parent_id)
  end

  def load_micropost
    @micropost = Micropost.find_by(id: params[:comment][:micropost_id])
    return if @micropost

    flash[:warning] = "k tim thay micropost"
    redirect_to root_path
  end

  def load_comment
    @comment = Comment.find_by id: params[:id]
    return if @comment

    flash[:warning] = t "khong tim thay id comment"
    redirect_to root_path
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card comment-card">
  <div class="card-body">
    <div class="row">
      <% if comment.parent_id.blank? %>
        <div class="col-md-1">
          <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid img-cmt"/>
        </div>
        <div class="col-md-11">
          <div class="clearfix"></div>
          <p>
            <a class="float-left" href="#"><strong><%= comment.name %></strong></a>
          </p>
          <p>
            <%= comment.content %>
          </p>
          <p class = "func-button">
            <%= link_to 'reply', new_comment_path(parent_id: comment.id), remote: true, class: 'btn btn-primary' %>
            <%= link_to 'edit', edit_comment_path(id: comment.id), remote: true ,class: "btn btn-primary" %>
            <%= link_to "destroy",comment_path(comment.id), method: :delete, data: { confirm: "ban co muon xoa comment" }, class: "btn btn-danger"%>
          </p>
          <p>
            <%= comment.created_at %>
          </p>
        </div>
      <% end %>
      <div class="reply">
        <div id="reply-form-<%= comment.id %>"></div>
        <div id="edit-form-<%= comment.id %>"></div>
        <% if comment.replies.any? %>
          <% comment.replies.each do |reply| %>
            <%= render partial: 'comments/reply', locals: { reply: reply } %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_for @comment do |f| %>
      <div class="form-group">
        <%= f.hidden_field :micropost_id, value: @micropost.id %>
        <%= f.label 'comment' %>
        <%= f.text_area :content, placeholder: "New Comment",required: true, class: 'form-control' %>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_for @comment do |f| %>
      <div class="form-group">
        <%= f.label 'Comment' %>
        <%= f.text_area :content, placeholder: "Update Comment",required: true, class: 'form-control'%>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/_reply.html.erb
<div class="card ml-5">
  <div class="card-body">
    <div class = "row reply">
      <div class="col-md-1 col-img">
        <img src="https://image.ibb.co/jw55Ex/def_face.jpg" class="img img-rounded img-fluid img-cmt"/>
      </div>
      <div class="col-md-11 col-content">
        <div class="clearfix"></div>
        <p>
          <a class="float-left" href="#"><strong><%= reply.name %></strong></a>
        </p>
        <p>
          <%= reply.content %>
        </p>
        <p>
          <%= link_to 'edit', edit_comment_path(reply.id) ,class: "btn btn-primary" %>
          <%= link_to "destroy",comment_path(reply.id), method: :delete, data: { confirm: "ban co muon xoa comment" }, class: "btn btn-danger"%></p>
        <p>
          <%= reply.created_at %>
        </p>
      </div>
    </div>
  </div>
</div>

app/views/comments/_reply_form.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_for @comment do |f| %>
      <div class="form-group">
        <%= f.hidden_field :micropost_id, value: @micropost.id %>
        <%= f.hidden_field :parent_id, value: @comment.parent_id %>
        <%= f.label 'Reply' %>
        <%= f.text_area :content, placeholder: "Reply Comment",required: true, class: 'form-control'%>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/edit.html.erb
<div class="card ml-5">
  <div class="card-body">
    <%= form_for @comment do |f| %>
      <div class="form-group">
        <%= f.label 'Comment' %>
        <%= f.text_area :content, placeholder: "Update Comment",required: true, class: 'form-control'%>
      </div>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/comments/edit.js.erb
document.querySelector("#edit-form-<%= @comment.id %>").innerHTML = ("<%= j render 'form', comment: @comment %>")

app/views/comments/new.js.erb
document.querySelector("#reply-form-<%= @comment.parent_id %>").innerHTML = ("<%= j render 'reply_form', comment: @comment %>")